// <auto-generated />
using System;
using IncidentesFISEI.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IncidentesFISEI.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251202223834_SistemaGestionConocimiento")]
    partial class SistemaGestionConocimiento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.ArchivoAdjunto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArticuloId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IncidenteId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NombreOriginal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SubidoPorId")
                        .HasColumnType("int");

                    b.Property<long>("TamañoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoMime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ArticuloId");

                    b.HasIndex("IncidenteId");

                    b.HasIndex("SubidoPorId");

                    b.ToTable("ArchivosAdjuntos");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.ArticuloConocimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EsSolucionValidada")
                        .HasColumnType("bit");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRevision")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Limitaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PasosDetallados")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<string>("Prerequisites")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Resumen")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("RevisadoPorId")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("TasaExito")
                        .HasColumnType("float");

                    b.Property<int>("TipoArticulo")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VecesUtilizado")
                        .HasColumnType("int");

                    b.Property<int>("VersionActual")
                        .HasColumnType("int");

                    b.Property<int>("Visualizaciones")
                        .HasColumnType("int");

                    b.Property<int>("VotosNegativos")
                        .HasColumnType("int");

                    b.Property<int>("VotosPositivos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("RevisadoPorId");

                    b.ToTable("ArticulosConocimiento");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.ArticuloEtiqueta", b =>
                {
                    b.Property<int>("ArticuloConocimientoId")
                        .HasColumnType("int");

                    b.Property<int>("EtiquetaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ArticuloConocimientoId", "EtiquetaId");

                    b.HasIndex("EtiquetaId");

                    b.ToTable("ArticulosEtiquetas");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.CategoriaIncidente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Icono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("TiempoResolucionMinutos")
                        .HasColumnType("int");

                    b.Property<int?>("TiempoRespuestaMinutos")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#dc3545",
                            CreatedAt = new DateTime(2025, 12, 2, 22, 38, 31, 988, DateTimeKind.Utc).AddTicks(6149),
                            Descripcion = "Problemas relacionados con hardware",
                            Icono = "fas fa-desktop",
                            IsActive = true,
                            IsDeleted = false,
                            Nombre = "Hardware",
                            TiempoResolucionMinutos = 240,
                            TiempoRespuestaMinutos = 30
                        },
                        new
                        {
                            Id = 2,
                            Color = "#007bff",
                            CreatedAt = new DateTime(2025, 12, 2, 22, 38, 31, 988, DateTimeKind.Utc).AddTicks(6292),
                            Descripcion = "Problemas relacionados con software",
                            Icono = "fas fa-code",
                            IsActive = true,
                            IsDeleted = false,
                            Nombre = "Software",
                            TiempoResolucionMinutos = 480,
                            TiempoRespuestaMinutos = 60
                        },
                        new
                        {
                            Id = 3,
                            Color = "#28a745",
                            CreatedAt = new DateTime(2025, 12, 2, 22, 38, 31, 988, DateTimeKind.Utc).AddTicks(6297),
                            Descripcion = "Problemas de conectividad y red",
                            Icono = "fas fa-network-wired",
                            IsActive = true,
                            IsDeleted = false,
                            Nombre = "Red",
                            TiempoResolucionMinutos = 120,
                            TiempoRespuestaMinutos = 15
                        },
                        new
                        {
                            Id = 4,
                            Color = "#ffc107",
                            CreatedAt = new DateTime(2025, 12, 2, 22, 38, 31, 988, DateTimeKind.Utc).AddTicks(6316),
                            Descripcion = "Problemas de autenticación y permisos",
                            Icono = "fas fa-lock",
                            IsActive = true,
                            IsDeleted = false,
                            Nombre = "Acceso",
                            TiempoResolucionMinutos = 180,
                            TiempoRespuestaMinutos = 45
                        },
                        new
                        {
                            Id = 5,
                            Color = "#17a2b8",
                            CreatedAt = new DateTime(2025, 12, 2, 22, 38, 31, 988, DateTimeKind.Utc).AddTicks(6319),
                            Descripcion = "Problemas con correo electrónico",
                            Icono = "fas fa-envelope",
                            IsActive = true,
                            IsDeleted = false,
                            Nombre = "Correo",
                            TiempoResolucionMinutos = 360,
                            TiempoRespuestaMinutos = 60
                        });
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.ComentarioArticulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticuloConocimientoId")
                        .HasColumnType("int");

                    b.Property<int?>("ComentarioPadreId")
                        .HasColumnType("int");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EsRespuesta")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArticuloConocimientoId");

                    b.HasIndex("ComentarioPadreId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ComentariosArticulo");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.ComentarioIncidente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EsInterno")
                        .HasColumnType("bit");

                    b.Property<int>("IncidenteId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("IncidenteId");

                    b.ToTable("ComentariosIncidente");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.EscalacionSLA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEscalacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FueNotificado")
                        .HasColumnType("bit");

                    b.Property<int>("IncidenteId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SLAId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IncidenteId");

                    b.HasIndex("SLAId");

                    b.ToTable("EscalacionesSLA");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.EtiquetaConocimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasDefaultValue("#007bff");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VecesUsada")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("EtiquetasConocimiento");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#0078D4",
                            CreatedAt = new DateTime(2025, 12, 2, 22, 38, 32, 15, DateTimeKind.Utc).AddTicks(4105),
                            IsDeleted = false,
                            Nombre = "Windows",
                            VecesUsada = 0
                        },
                        new
                        {
                            Id = 2,
                            Color = "#FCC624",
                            CreatedAt = new DateTime(2025, 12, 2, 22, 38, 32, 15, DateTimeKind.Utc).AddTicks(4113),
                            IsDeleted = false,
                            Nombre = "Linux",
                            VecesUsada = 0
                        },
                        new
                        {
                            Id = 3,
                            Color = "#00A4EF",
                            CreatedAt = new DateTime(2025, 12, 2, 22, 38, 32, 15, DateTimeKind.Utc).AddTicks(4115),
                            IsDeleted = false,
                            Nombre = "Redes",
                            VecesUsada = 0
                        },
                        new
                        {
                            Id = 4,
                            Color = "#FF5722",
                            CreatedAt = new DateTime(2025, 12, 2, 22, 38, 32, 15, DateTimeKind.Utc).AddTicks(4117),
                            IsDeleted = false,
                            Nombre = "Hardware",
                            VecesUsada = 0
                        },
                        new
                        {
                            Id = 5,
                            Color = "#4CAF50",
                            CreatedAt = new DateTime(2025, 12, 2, 22, 38, 32, 15, DateTimeKind.Utc).AddTicks(4119),
                            IsDeleted = false,
                            Nombre = "Software",
                            VecesUsada = 0
                        },
                        new
                        {
                            Id = 6,
                            Color = "#F44336",
                            CreatedAt = new DateTime(2025, 12, 2, 22, 38, 32, 15, DateTimeKind.Utc).AddTicks(4122),
                            IsDeleted = false,
                            Nombre = "Seguridad",
                            VecesUsada = 0
                        },
                        new
                        {
                            Id = 7,
                            Color = "#9C27B0",
                            CreatedAt = new DateTime(2025, 12, 2, 22, 38, 32, 15, DateTimeKind.Utc).AddTicks(4124),
                            IsDeleted = false,
                            Nombre = "Base de Datos",
                            VecesUsada = 0
                        },
                        new
                        {
                            Id = 8,
                            Color = "#607D8B",
                            CreatedAt = new DateTime(2025, 12, 2, 22, 38, 32, 15, DateTimeKind.Utc).AddTicks(4126),
                            IsDeleted = false,
                            Nombre = "Impresión",
                            VecesUsada = 0
                        },
                        new
                        {
                            Id = 9,
                            Color = "#FF9800",
                            CreatedAt = new DateTime(2025, 12, 2, 22, 38, 32, 15, DateTimeKind.Utc).AddTicks(4128),
                            IsDeleted = false,
                            Nombre = "Email",
                            VecesUsada = 0
                        },
                        new
                        {
                            Id = 10,
                            Color = "#3F51B5",
                            CreatedAt = new DateTime(2025, 12, 2, 22, 38, 32, 15, DateTimeKind.Utc).AddTicks(4130),
                            IsDeleted = false,
                            Nombre = "VPN",
                            VecesUsada = 0
                        });
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.HistorialEscalacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEscalacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FueAutomatico")
                        .HasColumnType("bit");

                    b.Property<int>("IncidenteId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("NivelDestino")
                        .HasColumnType("int");

                    b.Property<int>("NivelOrigen")
                        .HasColumnType("int");

                    b.Property<string>("Razon")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("TecnicoDestinoId")
                        .HasColumnType("int");

                    b.Property<int?>("TecnicoOrigenId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IncidenteId");

                    b.HasIndex("TecnicoDestinoId");

                    b.HasIndex("TecnicoOrigenId");

                    b.ToTable("HistorialEscalaciones");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.Incidente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivosAfectados")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("ArticuloConocimientoId")
                        .HasColumnType("int");

                    b.Property<int?>("AsignadoAId")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("CausaRaiz")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("EscaladoAutomaticamente")
                        .HasColumnType("bit");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicioTrabajo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaReporte")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimaEscalacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("Impacto")
                        .HasColumnType("int");

                    b.Property<string>("ImpactoDetallado")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("NivelActual")
                        .HasColumnType("int");

                    b.Property<int>("NumeroEscalaciones")
                        .HasColumnType("int");

                    b.Property<string>("NumeroIncidente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PasosReproducir")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.Property<string>("RazonEscalacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReportadoPorId")
                        .HasColumnType("int");

                    b.Property<int?>("ServicioDITICId")
                        .HasColumnType("int");

                    b.Property<string>("Solucion")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Urgencia")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArticuloConocimientoId");

                    b.HasIndex("AsignadoAId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("NumeroIncidente")
                        .IsUnique();

                    b.HasIndex("ReportadoPorId");

                    b.HasIndex("ServicioDITICId");

                    b.ToTable("Incidentes");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.IncidenteRelacionado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IncidentePrincipalId")
                        .HasColumnType("int");

                    b.Property<int>("IncidenteRelacionadoId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("TipoRelacion")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IncidentePrincipalId");

                    b.HasIndex("IncidenteRelacionadoId");

                    b.ToTable("IncidentesRelacionados");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.RegistroTiempo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IncidenteId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("TecnicoId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("TiempoTranscurrido")
                        .HasColumnType("time");

                    b.Property<int>("TipoActividad")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IncidenteId");

                    b.HasIndex("TecnicoId");

                    b.ToTable("RegistrosTiempo");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.SLA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Impacto")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.Property<int>("TiempoResolucion")
                        .HasColumnType("int");

                    b.Property<int>("TiempoRespuesta")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Urgencia")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SLAs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 2, 22, 38, 32, 2, DateTimeKind.Utc).AddTicks(6797),
                            Descripcion = "SLA para incidentes críticos",
                            Impacto = 4,
                            IsActive = true,
                            IsDeleted = false,
                            Nombre = "Crítico",
                            Prioridad = 4,
                            TiempoResolucion = 60,
                            TiempoRespuesta = 15,
                            Urgencia = 4
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 2, 22, 38, 32, 2, DateTimeKind.Utc).AddTicks(6805),
                            Descripcion = "SLA para incidentes de alta prioridad",
                            Impacto = 3,
                            IsActive = true,
                            IsDeleted = false,
                            Nombre = "Alto",
                            Prioridad = 3,
                            TiempoResolucion = 120,
                            TiempoRespuesta = 30,
                            Urgencia = 3
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 2, 22, 38, 32, 2, DateTimeKind.Utc).AddTicks(6822),
                            Descripcion = "SLA para incidentes de prioridad media",
                            Impacto = 2,
                            IsActive = true,
                            IsDeleted = false,
                            Nombre = "Medio",
                            Prioridad = 2,
                            TiempoResolucion = 480,
                            TiempoRespuesta = 60,
                            Urgencia = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 12, 2, 22, 38, 32, 2, DateTimeKind.Utc).AddTicks(6825),
                            Descripcion = "SLA para incidentes de baja prioridad",
                            Impacto = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Nombre = "Bajo",
                            Prioridad = 1,
                            TiempoResolucion = 2880,
                            TiempoRespuesta = 240,
                            Urgencia = 1
                        });
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.ServicioDITIC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("CostoEstimado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DescripcionDetallada")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("DocumentacionURL")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("EsServicioEsencial")
                        .HasColumnType("bit");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaFinServicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicioServicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("HorarioDisponibilidad")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Limitaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("PorcentajeDisponibilidad")
                        .HasColumnType("float");

                    b.Property<string>("Requisitos")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("ResponsableNegocioId")
                        .HasColumnType("int");

                    b.Property<int?>("ResponsableTecnicoId")
                        .HasColumnType("int");

                    b.Property<int?>("SLAId")
                        .HasColumnType("int");

                    b.Property<int>("TipoServicio")
                        .HasColumnType("int");

                    b.Property<string>("UnidadCosto")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("ResponsableNegocioId");

                    b.HasIndex("ResponsableTecnicoId");

                    b.HasIndex("SLAId");

                    b.ToTable("ServiciosDITIC");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 3,
                            Codigo = "SRV-001",
                            CreatedAt = new DateTime(2025, 12, 2, 22, 38, 32, 2, DateTimeKind.Utc).AddTicks(9742),
                            Descripcion = "Conectividad WiFi en todas las instalaciones de FISEI",
                            DescripcionDetallada = "Servicio de acceso inalámbrico a internet para estudiantes, docentes y personal administrativo en todo el campus de FISEI.",
                            EsServicioEsencial = true,
                            EstaActivo = true,
                            FechaInicioServicio = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HorarioDisponibilidad = "24/7",
                            IsDeleted = false,
                            Nombre = "Acceso a Internet WiFi",
                            PorcentajeDisponibilidad = 99.0,
                            Requisitos = "Credenciales institucionales UTA",
                            ResponsableTecnicoId = 2,
                            SLAId = 2,
                            TipoServicio = 10
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 5,
                            Codigo = "SRV-002",
                            CreatedAt = new DateTime(2025, 12, 2, 22, 38, 32, 2, DateTimeKind.Utc).AddTicks(9892),
                            Descripcion = "Servicio de correo electrónico @fisei.uta.edu.ec",
                            DescripcionDetallada = "Cuentas de correo institucional con 50GB de almacenamiento, integración con Office 365 y servicios en la nube.",
                            EsServicioEsencial = true,
                            EstaActivo = true,
                            FechaInicioServicio = new DateTime(2019, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HorarioDisponibilidad = "24/7",
                            IsDeleted = false,
                            Limitaciones = "Cuota de 50GB, políticas anti-spam aplicables",
                            Nombre = "Correo Institucional",
                            PorcentajeDisponibilidad = 99.900000000000006,
                            Requisitos = "Ser estudiante, docente o administrativo activo",
                            ResponsableTecnicoId = 2,
                            SLAId = 1,
                            TipoServicio = 5
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 1,
                            Codigo = "SRV-003",
                            CreatedAt = new DateTime(2025, 12, 2, 22, 38, 32, 2, DateTimeKind.Utc).AddTicks(9900),
                            Descripcion = "Acceso a laboratorios con equipos especializados",
                            DescripcionDetallada = "5 laboratorios equipados con 150+ computadoras con software especializado para ingeniería (MATLAB, AutoCAD, IDEs, etc.)",
                            EsServicioEsencial = true,
                            EstaActivo = true,
                            FechaInicioServicio = new DateTime(2018, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HorarioDisponibilidad = "Lunes a Viernes 7:00-21:00, Sábados 8:00-13:00",
                            IsDeleted = false,
                            Limitaciones = "Capacidad limitada, requiere reserva para uso fuera de horario de clase",
                            Nombre = "Laboratorios de Computación",
                            PorcentajeDisponibilidad = 98.0,
                            Requisitos = "Horario asignado por materia o reserva previa",
                            ResponsableTecnicoId = 3,
                            SLAId = 3,
                            TipoServicio = 9
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "SRV-004",
                            CreatedAt = new DateTime(2025, 12, 2, 22, 38, 32, 2, DateTimeKind.Utc).AddTicks(9905),
                            Descripcion = "Mesa de ayuda para problemas técnicos",
                            DescripcionDetallada = "Atención personalizada para resolver problemas de hardware, software, acceso a sistemas y otros inconvenientes técnicos.",
                            EsServicioEsencial = true,
                            EstaActivo = true,
                            FechaInicioServicio = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HorarioDisponibilidad = "Lunes a Viernes 8:00-17:00",
                            IsDeleted = false,
                            Nombre = "Soporte Técnico Help Desk",
                            PorcentajeDisponibilidad = 100.0,
                            Requisitos = "Ninguno - servicio abierto a toda la comunidad FISEI",
                            ResponsableTecnicoId = 2,
                            SLAId = 2,
                            TipoServicio = 3
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 2,
                            Codigo = "SRV-005",
                            CreatedAt = new DateTime(2025, 12, 2, 22, 38, 32, 2, DateTimeKind.Utc).AddTicks(9910),
                            Descripcion = "Plataforma para registro de calificaciones y gestión académica",
                            DescripcionDetallada = "Sistema integral para gestión de matrículas, calificaciones, horarios, y seguimiento académico de estudiantes.",
                            EsServicioEsencial = true,
                            EstaActivo = true,
                            FechaInicioServicio = new DateTime(2017, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HorarioDisponibilidad = "24/7",
                            IsDeleted = false,
                            Limitaciones = "Mantenimiento programado los domingos 2:00-4:00 AM",
                            Nombre = "Sistema de Gestión Académica",
                            PorcentajeDisponibilidad = 99.5,
                            Requisitos = "Credenciales institucionales",
                            ResponsableTecnicoId = 2,
                            SLAId = 1,
                            TipoServicio = 2
                        },
                        new
                        {
                            Id = 6,
                            CategoriaId = 2,
                            Codigo = "SRV-006",
                            CreatedAt = new DateTime(2025, 12, 2, 22, 38, 32, 3, DateTimeKind.Utc).AddTicks(64),
                            Descripcion = "Plataforma de aprendizaje en línea",
                            DescripcionDetallada = "Sistema LMS para gestión de cursos virtuales, tareas, foros, evaluaciones y recursos educativos digitales.",
                            DocumentacionURL = "https://aulavirtual.fisei.uta.edu.ec/ayuda",
                            EsServicioEsencial = true,
                            EstaActivo = true,
                            FechaInicioServicio = new DateTime(2016, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HorarioDisponibilidad = "24/7",
                            IsDeleted = false,
                            Nombre = "Aula Virtual (Moodle)",
                            PorcentajeDisponibilidad = 99.0,
                            Requisitos = "Estar matriculado o ser docente activo",
                            ResponsableTecnicoId = 2,
                            SLAId = 2,
                            TipoServicio = 2
                        },
                        new
                        {
                            Id = 7,
                            CategoriaId = 1,
                            Codigo = "SRV-007",
                            CostoEstimado = 0.05m,
                            CreatedAt = new DateTime(2025, 12, 2, 22, 38, 32, 3, DateTimeKind.Utc).AddTicks(859),
                            Descripcion = "Servicio de impresión para trabajos académicos",
                            DescripcionDetallada = "Red de impresoras multifunción disponibles para estudiantes y docentes. Incluye impresión, escaneo y fotocopiado.",
                            EsServicioEsencial = false,
                            EstaActivo = true,
                            FechaInicioServicio = new DateTime(2019, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HorarioDisponibilidad = "Lunes a Viernes 8:00-18:00",
                            IsDeleted = false,
                            Limitaciones = "Máximo 50 páginas por día por usuario",
                            Nombre = "Impresión y Fotocopiado",
                            PorcentajeDisponibilidad = 95.0,
                            Requisitos = "Credenciales institucionales, cuota de impresión prepagada",
                            ResponsableTecnicoId = 4,
                            SLAId = 3,
                            TipoServicio = 9,
                            UnidadCosto = "por página B/N"
                        },
                        new
                        {
                            Id = 8,
                            CategoriaId = 3,
                            Codigo = "SRV-008",
                            CreatedAt = new DateTime(2025, 12, 2, 22, 38, 32, 3, DateTimeKind.Utc).AddTicks(868),
                            Descripcion = "Acceso remoto seguro a recursos internos",
                            DescripcionDetallada = "Red privada virtual para acceder a recursos institucionales (bibliotecas digitales, sistemas internos) desde fuera del campus.",
                            DocumentacionURL = "https://ditic.uta.edu.ec/vpn",
                            EsServicioEsencial = false,
                            EstaActivo = true,
                            FechaInicioServicio = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HorarioDisponibilidad = "24/7",
                            IsDeleted = false,
                            Limitaciones = "Acceso limitado a docentes e investigadores",
                            Nombre = "VPN Institucional",
                            PorcentajeDisponibilidad = 98.0,
                            Requisitos = "Solicitud previa, credenciales institucionales",
                            ResponsableTecnicoId = 2,
                            SLAId = 3,
                            TipoServicio = 4
                        },
                        new
                        {
                            Id = 9,
                            CategoriaId = 2,
                            Codigo = "SRV-009",
                            CreatedAt = new DateTime(2025, 12, 2, 22, 38, 32, 3, DateTimeKind.Utc).AddTicks(873),
                            Descripcion = "Almacenamiento de trabajos de titulación y publicaciones",
                            DescripcionDetallada = "Plataforma para almacenar, preservar y difundir la producción académica de FISEI (tesis, papers, proyectos).",
                            DocumentacionURL = "https://repositorio.uta.edu.ec",
                            EsServicioEsencial = false,
                            EstaActivo = true,
                            FechaInicioServicio = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HorarioDisponibilidad = "24/7",
                            IsDeleted = false,
                            Nombre = "Repositorio Digital Institucional",
                            PorcentajeDisponibilidad = 99.5,
                            Requisitos = "Aprobación del tutor y defensa del trabajo",
                            ResponsableTecnicoId = 2,
                            SLAId = 4,
                            TipoServicio = 6
                        },
                        new
                        {
                            Id = 10,
                            CategoriaId = 2,
                            Codigo = "SRV-010",
                            CreatedAt = new DateTime(2025, 12, 2, 22, 38, 32, 3, DateTimeKind.Utc).AddTicks(878),
                            Descripcion = "Acceso a software especializado con licencia institucional",
                            DescripcionDetallada = "Provisión de licencias para software de ingeniería: MATLAB, Autodesk, Microsoft Office 365, JetBrains, Visual Studio, etc.",
                            EsServicioEsencial = true,
                            EstaActivo = true,
                            FechaInicioServicio = new DateTime(2018, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HorarioDisponibilidad = "24/7 (activación)",
                            IsDeleted = false,
                            Limitaciones = "Licencias limitadas según convenios vigentes",
                            Nombre = "Licencias de Software Académico",
                            PorcentajeDisponibilidad = 99.0,
                            Requisitos = "Ser estudiante o docente activo, solicitud por correo institucional",
                            ResponsableTecnicoId = 2,
                            SLAId = 3,
                            TipoServicio = 2
                        });
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AñosExperiencia")
                        .HasColumnType("int");

                    b.Property<int>("CargaTrabajoActual")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Especialidad")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSPOC")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("NivelSoporte")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CargaTrabajoActual = 0,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "FISEI",
                            Email = "admin@fisei.uta.edu.ec",
                            FirstName = "Administrador",
                            IsActive = true,
                            IsAvailable = true,
                            IsDeleted = false,
                            IsEmailConfirmed = true,
                            IsSPOC = false,
                            LastName = "Sistema",
                            PasswordHash = "$2a$11$KjLnhQkoD9HBy0sZQaxvKe5sBoELZbldjM1ywnR.wn9aAgOOXQr1K",
                            TipoUsuario = 4,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            AñosExperiencia = 8,
                            CargaTrabajoActual = 0,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Soporte Técnico",
                            Email = "supervisor@fisei.uta.edu.ec",
                            Especialidad = "Redes y Sistemas",
                            FirstName = "Carlos",
                            IsActive = true,
                            IsAvailable = true,
                            IsDeleted = false,
                            IsEmailConfirmed = true,
                            IsSPOC = false,
                            LastName = "Mendoza",
                            PasswordHash = "$2a$11$r9PuDRz5A1J/7FHn3AXd5.Zg/AOUy0Ok/8sDSxJEKVGJYtFRlUdOK",
                            TipoUsuario = 3,
                            Username = "supervisor1"
                        },
                        new
                        {
                            Id = 3,
                            AñosExperiencia = 3,
                            CargaTrabajoActual = 0,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Soporte Técnico",
                            Email = "tecnico1@fisei.uta.edu.ec",
                            Especialidad = "Hardware y Software",
                            FirstName = "María",
                            IsActive = true,
                            IsAvailable = true,
                            IsDeleted = false,
                            IsEmailConfirmed = true,
                            IsSPOC = false,
                            LastName = "González",
                            PasswordHash = "$2a$11$wxqje4Ox3VO3RGljJA9Vp.9WByK3DpGbgDt2Bfde5awiLFBlY7.0e",
                            TipoUsuario = 2,
                            Username = "tecnico1"
                        },
                        new
                        {
                            Id = 4,
                            AñosExperiencia = 5,
                            CargaTrabajoActual = 0,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Soporte Técnico",
                            Email = "tecnico2@fisei.uta.edu.ec",
                            Especialidad = "Redes y Conectividad",
                            FirstName = "Luis",
                            IsActive = true,
                            IsAvailable = true,
                            IsDeleted = false,
                            IsEmailConfirmed = true,
                            IsSPOC = false,
                            LastName = "Ramírez",
                            PasswordHash = "$2a$11$9f5rP2P5qP5qP5qP5qP5qP5qP5qP5qP5qP5qP5qP5qP5qP5qP5qP5q",
                            TipoUsuario = 2,
                            Username = "tecnico2"
                        },
                        new
                        {
                            Id = 5,
                            CargaTrabajoActual = 0,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Ingeniería en Sistemas",
                            Email = "docente1@fisei.uta.edu.ec",
                            FirstName = "Ana",
                            IsActive = true,
                            IsAvailable = true,
                            IsDeleted = false,
                            IsEmailConfirmed = true,
                            IsSPOC = false,
                            LastName = "Pérez",
                            PasswordHash = "$2a$11$fS7059bDQD23mvMoKYCjoOvs7umhzDvu5tOW.lGwA7y6gzUWaNGo.",
                            Phone = "0998123456",
                            TipoUsuario = 1,
                            Username = "docente1"
                        },
                        new
                        {
                            Id = 6,
                            CargaTrabajoActual = 0,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Ingeniería en Sistemas",
                            Email = "estudiante1@fisei.uta.edu.ec",
                            FirstName = "José",
                            IsActive = false,
                            IsAvailable = true,
                            IsDeleted = false,
                            IsEmailConfirmed = false,
                            IsSPOC = false,
                            LastName = "Morales",
                            PasswordHash = "$2a$11$9f5rP2P5qP5qP5qP5qP5qP5qP5qP5qP5qP5qP5qP5qP5qP5qP5qP5q",
                            TipoUsuario = 1,
                            Username = "estudiante1"
                        },
                        new
                        {
                            Id = 7,
                            CargaTrabajoActual = 0,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Ingeniería Industrial",
                            Email = "estudiante2@fisei.uta.edu.ec",
                            FirstName = "Carmen",
                            IsActive = false,
                            IsAvailable = true,
                            IsDeleted = false,
                            IsEmailConfirmed = false,
                            IsSPOC = false,
                            LastName = "Torres",
                            PasswordHash = "$2a$11$9f5rP2P5qP5qP5qP5qP5qP5qP5qP5qP5qP5qP5qP5qP5qP5qP5qP5q",
                            TipoUsuario = 1,
                            Username = "estudiante2"
                        });
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.ValidacionArticulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aprobado")
                        .HasColumnType("bit");

                    b.Property<int>("ArticuloConocimientoId")
                        .HasColumnType("int");

                    b.Property<string>("ComentariosValidador")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaValidacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("SolicitadoPorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ValidadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArticuloConocimientoId");

                    b.HasIndex("SolicitadoPorId");

                    b.HasIndex("ValidadorId");

                    b.ToTable("ValidacionesArticulo");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.VersionArticulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticuloConocimientoId")
                        .HasColumnType("int");

                    b.Property<string>("CambiosRealizados")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVersion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ModificadoPorId")
                        .HasColumnType("int");

                    b.Property<int>("NumeroVersion")
                        .HasColumnType("int");

                    b.Property<string>("Resumen")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ArticuloConocimientoId");

                    b.HasIndex("ModificadoPorId");

                    b.ToTable("VersionesArticulo");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.VotacionArticulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticuloConocimientoId")
                        .HasColumnType("int");

                    b.Property<string>("Comentario")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("Voto")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ArticuloConocimientoId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("VotacionesArticulo");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.ArchivoAdjunto", b =>
                {
                    b.HasOne("IncidentesFISEI.Domain.Entities.ArticuloConocimiento", "Articulo")
                        .WithMany("ArchivosAdjuntos")
                        .HasForeignKey("ArticuloId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IncidentesFISEI.Domain.Entities.Incidente", "Incidente")
                        .WithMany("ArchivosAdjuntos")
                        .HasForeignKey("IncidenteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IncidentesFISEI.Domain.Entities.Usuario", "SubidoPor")
                        .WithMany()
                        .HasForeignKey("SubidoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("Incidente");

                    b.Navigation("SubidoPor");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.ArticuloConocimiento", b =>
                {
                    b.HasOne("IncidentesFISEI.Domain.Entities.Usuario", "Autor")
                        .WithMany("ArticulosCreados")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IncidentesFISEI.Domain.Entities.CategoriaIncidente", "Categoria")
                        .WithMany("ArticulosConocimiento")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IncidentesFISEI.Domain.Entities.Usuario", "RevisadoPor")
                        .WithMany()
                        .HasForeignKey("RevisadoPorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Autor");

                    b.Navigation("Categoria");

                    b.Navigation("RevisadoPor");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.ArticuloEtiqueta", b =>
                {
                    b.HasOne("IncidentesFISEI.Domain.Entities.ArticuloConocimiento", "ArticuloConocimiento")
                        .WithMany("ArticulosEtiquetas")
                        .HasForeignKey("ArticuloConocimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IncidentesFISEI.Domain.Entities.EtiquetaConocimiento", "Etiqueta")
                        .WithMany("ArticulosEtiquetas")
                        .HasForeignKey("EtiquetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArticuloConocimiento");

                    b.Navigation("Etiqueta");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.CategoriaIncidente", b =>
                {
                    b.HasOne("IncidentesFISEI.Domain.Entities.CategoriaIncidente", "ParentCategory")
                        .WithMany("SubCategorias")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.ComentarioArticulo", b =>
                {
                    b.HasOne("IncidentesFISEI.Domain.Entities.ArticuloConocimiento", "ArticuloConocimiento")
                        .WithMany("Comentarios")
                        .HasForeignKey("ArticuloConocimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IncidentesFISEI.Domain.Entities.ComentarioArticulo", "ComentarioPadre")
                        .WithMany("Respuestas")
                        .HasForeignKey("ComentarioPadreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IncidentesFISEI.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ArticuloConocimiento");

                    b.Navigation("ComentarioPadre");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.ComentarioIncidente", b =>
                {
                    b.HasOne("IncidentesFISEI.Domain.Entities.Usuario", "Autor")
                        .WithMany("Comentarios")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IncidentesFISEI.Domain.Entities.Incidente", "Incidente")
                        .WithMany("Comentarios")
                        .HasForeignKey("IncidenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Incidente");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.EscalacionSLA", b =>
                {
                    b.HasOne("IncidentesFISEI.Domain.Entities.Incidente", "Incidente")
                        .WithMany()
                        .HasForeignKey("IncidenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IncidentesFISEI.Domain.Entities.SLA", "SLA")
                        .WithMany()
                        .HasForeignKey("SLAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Incidente");

                    b.Navigation("SLA");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.HistorialEscalacion", b =>
                {
                    b.HasOne("IncidentesFISEI.Domain.Entities.Incidente", "Incidente")
                        .WithMany()
                        .HasForeignKey("IncidenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IncidentesFISEI.Domain.Entities.Usuario", "TecnicoDestino")
                        .WithMany()
                        .HasForeignKey("TecnicoDestinoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IncidentesFISEI.Domain.Entities.Usuario", "TecnicoOrigen")
                        .WithMany()
                        .HasForeignKey("TecnicoOrigenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Incidente");

                    b.Navigation("TecnicoDestino");

                    b.Navigation("TecnicoOrigen");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.Incidente", b =>
                {
                    b.HasOne("IncidentesFISEI.Domain.Entities.ArticuloConocimiento", "ArticuloConocimiento")
                        .WithMany("IncidentesRelacionados")
                        .HasForeignKey("ArticuloConocimientoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IncidentesFISEI.Domain.Entities.Usuario", "AsignadoA")
                        .WithMany("IncidentesAsignados")
                        .HasForeignKey("AsignadoAId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IncidentesFISEI.Domain.Entities.CategoriaIncidente", "Categoria")
                        .WithMany("Incidentes")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IncidentesFISEI.Domain.Entities.Usuario", "ReportadoPor")
                        .WithMany("IncidentesReportados")
                        .HasForeignKey("ReportadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IncidentesFISEI.Domain.Entities.ServicioDITIC", "ServicioDITIC")
                        .WithMany("IncidentesRelacionados")
                        .HasForeignKey("ServicioDITICId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ArticuloConocimiento");

                    b.Navigation("AsignadoA");

                    b.Navigation("Categoria");

                    b.Navigation("ReportadoPor");

                    b.Navigation("ServicioDITIC");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.IncidenteRelacionado", b =>
                {
                    b.HasOne("IncidentesFISEI.Domain.Entities.Incidente", "IncidentePrincipal")
                        .WithMany("IncidentesRelacionados")
                        .HasForeignKey("IncidentePrincipalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IncidentesFISEI.Domain.Entities.Incidente", "IncidenteRef")
                        .WithMany()
                        .HasForeignKey("IncidenteRelacionadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IncidentePrincipal");

                    b.Navigation("IncidenteRef");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.RegistroTiempo", b =>
                {
                    b.HasOne("IncidentesFISEI.Domain.Entities.Incidente", "Incidente")
                        .WithMany("RegistrosTiempo")
                        .HasForeignKey("IncidenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IncidentesFISEI.Domain.Entities.Usuario", "Tecnico")
                        .WithMany()
                        .HasForeignKey("TecnicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Incidente");

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.ServicioDITIC", b =>
                {
                    b.HasOne("IncidentesFISEI.Domain.Entities.CategoriaIncidente", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IncidentesFISEI.Domain.Entities.Usuario", "ResponsableNegocio")
                        .WithMany()
                        .HasForeignKey("ResponsableNegocioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IncidentesFISEI.Domain.Entities.Usuario", "ResponsableTecnico")
                        .WithMany()
                        .HasForeignKey("ResponsableTecnicoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IncidentesFISEI.Domain.Entities.SLA", "SLA")
                        .WithMany()
                        .HasForeignKey("SLAId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categoria");

                    b.Navigation("ResponsableNegocio");

                    b.Navigation("ResponsableTecnico");

                    b.Navigation("SLA");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.ValidacionArticulo", b =>
                {
                    b.HasOne("IncidentesFISEI.Domain.Entities.ArticuloConocimiento", "ArticuloConocimiento")
                        .WithMany("Validaciones")
                        .HasForeignKey("ArticuloConocimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IncidentesFISEI.Domain.Entities.Usuario", "SolicitadoPor")
                        .WithMany()
                        .HasForeignKey("SolicitadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IncidentesFISEI.Domain.Entities.Usuario", "Validador")
                        .WithMany()
                        .HasForeignKey("ValidadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ArticuloConocimiento");

                    b.Navigation("SolicitadoPor");

                    b.Navigation("Validador");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.VersionArticulo", b =>
                {
                    b.HasOne("IncidentesFISEI.Domain.Entities.ArticuloConocimiento", "ArticuloConocimiento")
                        .WithMany("Versiones")
                        .HasForeignKey("ArticuloConocimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IncidentesFISEI.Domain.Entities.Usuario", "ModificadoPor")
                        .WithMany()
                        .HasForeignKey("ModificadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ArticuloConocimiento");

                    b.Navigation("ModificadoPor");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.VotacionArticulo", b =>
                {
                    b.HasOne("IncidentesFISEI.Domain.Entities.ArticuloConocimiento", "ArticuloConocimiento")
                        .WithMany("Votaciones")
                        .HasForeignKey("ArticuloConocimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IncidentesFISEI.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ArticuloConocimiento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.ArticuloConocimiento", b =>
                {
                    b.Navigation("ArchivosAdjuntos");

                    b.Navigation("ArticulosEtiquetas");

                    b.Navigation("Comentarios");

                    b.Navigation("IncidentesRelacionados");

                    b.Navigation("Validaciones");

                    b.Navigation("Versiones");

                    b.Navigation("Votaciones");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.CategoriaIncidente", b =>
                {
                    b.Navigation("ArticulosConocimiento");

                    b.Navigation("Incidentes");

                    b.Navigation("SubCategorias");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.ComentarioArticulo", b =>
                {
                    b.Navigation("Respuestas");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.EtiquetaConocimiento", b =>
                {
                    b.Navigation("ArticulosEtiquetas");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.Incidente", b =>
                {
                    b.Navigation("ArchivosAdjuntos");

                    b.Navigation("Comentarios");

                    b.Navigation("IncidentesRelacionados");

                    b.Navigation("RegistrosTiempo");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.ServicioDITIC", b =>
                {
                    b.Navigation("IncidentesRelacionados");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("ArticulosCreados");

                    b.Navigation("Comentarios");

                    b.Navigation("IncidentesAsignados");

                    b.Navigation("IncidentesReportados");
                });
#pragma warning restore 612, 618
        }
    }
}
