// <auto-generated />
using System;
using IncidentesFISEI.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IncidentesFISEI.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Modern_Spanish_CI_AS")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.ArchivoAdjunto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArticuloId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IncidenteId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NombreOriginal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SubidoPorId")
                        .HasColumnType("int");

                    b.Property<long>("TamañoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoMime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ArticuloId");

                    b.HasIndex("IncidenteId");

                    b.HasIndex("SubidoPorId");

                    b.ToTable("ArchivosAdjuntos");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.ArticuloConocimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EsSolucionValidada")
                        .HasColumnType("bit");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRevision")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Limitaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PasosDetallados")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<string>("Prerequisites")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Resumen")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("RevisadoPorId")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Visualizaciones")
                        .HasColumnType("int");

                    b.Property<int>("VotosNegativos")
                        .HasColumnType("int");

                    b.Property<int>("VotosPositivos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("RevisadoPorId");

                    b.ToTable("ArticulosConocimiento");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.CategoriaIncidente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Icono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("TiempoResolucionMinutos")
                        .HasColumnType("int");

                    b.Property<int?>("TiempoRespuestaMinutos")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#dc3545",
                            CreatedAt = new DateTime(2025, 12, 5, 2, 26, 28, 641, DateTimeKind.Utc).AddTicks(3339),
                            Descripcion = "Problemas relacionados con hardware",
                            Icono = "fas fa-desktop",
                            IsActive = true,
                            IsDeleted = false,
                            Nombre = "Hardware",
                            TiempoResolucionMinutos = 240,
                            TiempoRespuestaMinutos = 30
                        },
                        new
                        {
                            Id = 2,
                            Color = "#007bff",
                            CreatedAt = new DateTime(2025, 12, 5, 2, 26, 28, 641, DateTimeKind.Utc).AddTicks(3461),
                            Descripcion = "Problemas relacionados con software",
                            Icono = "fas fa-code",
                            IsActive = true,
                            IsDeleted = false,
                            Nombre = "Software",
                            TiempoResolucionMinutos = 480,
                            TiempoRespuestaMinutos = 60
                        },
                        new
                        {
                            Id = 3,
                            Color = "#28a745",
                            CreatedAt = new DateTime(2025, 12, 5, 2, 26, 28, 641, DateTimeKind.Utc).AddTicks(3464),
                            Descripcion = "Problemas de conectividad y red",
                            Icono = "fas fa-network-wired",
                            IsActive = true,
                            IsDeleted = false,
                            Nombre = "Red",
                            TiempoResolucionMinutos = 120,
                            TiempoRespuestaMinutos = 15
                        },
                        new
                        {
                            Id = 4,
                            Color = "#ffc107",
                            CreatedAt = new DateTime(2025, 12, 5, 2, 26, 28, 641, DateTimeKind.Utc).AddTicks(3466),
                            Descripcion = "Problemas de autenticación y permisos",
                            Icono = "fas fa-lock",
                            IsActive = true,
                            IsDeleted = false,
                            Nombre = "Acceso",
                            TiempoResolucionMinutos = 180,
                            TiempoRespuestaMinutos = 45
                        },
                        new
                        {
                            Id = 5,
                            Color = "#17a2b8",
                            CreatedAt = new DateTime(2025, 12, 5, 2, 26, 28, 641, DateTimeKind.Utc).AddTicks(3468),
                            Descripcion = "Problemas con correo electrónico",
                            Icono = "fas fa-envelope",
                            IsActive = true,
                            IsDeleted = false,
                            Nombre = "Correo",
                            TiempoResolucionMinutos = 360,
                            TiempoRespuestaMinutos = 60
                        });
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.ComentarioArticulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticuloId")
                        .HasColumnType("int");

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Puntuacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ArticuloId");

                    b.HasIndex("AutorId");

                    b.ToTable("ComentariosArticulo");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.ComentarioIncidente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EsInterno")
                        .HasColumnType("bit");

                    b.Property<int>("IncidenteId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("IncidenteId");

                    b.ToTable("ComentariosIncidente");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.ConfiguracionNotificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly?>("HoraFinSilencioso")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("HoraInicioSilencioso")
                        .HasColumnType("time");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("NotificacionInmediata")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("NotificarEnSistema")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("NotificarPorEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("NotificarPorSMS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("ResumenDiario")
                        .HasColumnType("bit");

                    b.Property<bool>("ResumenSemanal")
                        .HasColumnType("bit");

                    b.Property<bool>("SoloIncidentesAsignados")
                        .HasColumnType("bit");

                    b.Property<int?>("SoloPrioridad")
                        .HasColumnType("int");

                    b.Property<int>("TipoEvento")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "TipoEvento")
                        .IsUnique();

                    b.ToTable("ConfiguracionesNotificacion");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.EscalacionSLA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEscalacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FueNotificado")
                        .HasColumnType("bit");

                    b.Property<int>("IncidenteId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SLAId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IncidenteId");

                    b.HasIndex("SLAId");

                    b.ToTable("EscalacionesSLA");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.Incidente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivosAfectados")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("ArticuloConocimientoId")
                        .HasColumnType("int");

                    b.Property<int?>("AsignadoAId")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("CausaRaiz")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("CerradoPorId")
                        .HasColumnType("int");

                    b.Property<string>("ComentarioCierre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicioTrabajo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaReapertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaReporte")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("Impacto")
                        .HasColumnType("int");

                    b.Property<string>("ImpactoDetallado")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MotivoReapertura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroIncidente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PasosReproducir")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.Property<int?>("ReabiertoPorId")
                        .HasColumnType("int");

                    b.Property<int>("ReportadoPorId")
                        .HasColumnType("int");

                    b.Property<int?>("ServicioId")
                        .HasColumnType("int");

                    b.Property<string>("Solucion")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Urgencia")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArticuloConocimientoId");

                    b.HasIndex("AsignadoAId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CerradoPorId");

                    b.HasIndex("NumeroIncidente")
                        .IsUnique();

                    b.HasIndex("ReabiertoPorId");

                    b.HasIndex("ReportadoPorId");

                    b.HasIndex("ServicioId");

                    b.ToTable("Incidentes");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.IncidenteRelacionado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IncidentePrincipalId")
                        .HasColumnType("int");

                    b.Property<int>("IncidenteRelacionadoId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("TipoRelacion")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IncidentePrincipalId");

                    b.HasIndex("IncidenteRelacionadoId");

                    b.ToTable("IncidentesRelacionados");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.LogNotificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Canal")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DireccionDestino")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ErrorDetalle")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaIntento")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdExterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MensajeError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NotificacionId")
                        .HasColumnType("int");

                    b.Property<int>("NumeroReintentos")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ProximoReintento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NotificacionId");

                    b.HasIndex("Estado", "FechaIntento");

                    b.ToTable("LogsNotificacion");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DatosAdicionales")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorEnvio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaEnvioEmail")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEnvioSMS")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaLectura")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IncidenteId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("Leida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("NotificadoPorEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("NotificadoPorSMS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.Property<int>("TipoNotificacion")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UrlAccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IncidenteId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UsuarioId", "Leida");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.PlantillaNotificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PlantillaEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlantillaMensaje")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<string>("PlantillaSMS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlantillaTitulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TipoNotificacion")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VariablesDisponibles")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TipoNotificacion", "IsActive")
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("PlantillasNotificacion");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.RegistroTiempo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IncidenteId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("TecnicoId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("TiempoTranscurrido")
                        .HasColumnType("time");

                    b.Property<int>("TipoActividad")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IncidenteId");

                    b.HasIndex("TecnicoId");

                    b.ToTable("RegistrosTiempo");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.SLA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Impacto")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.Property<int>("TiempoResolucion")
                        .HasColumnType("int");

                    b.Property<int>("TiempoRespuesta")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Urgencia")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SLAs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 5, 2, 26, 28, 642, DateTimeKind.Utc).AddTicks(1873),
                            Descripcion = "SLA para incidentes críticos",
                            Impacto = 4,
                            IsActive = true,
                            IsDeleted = false,
                            Nombre = "Crítico",
                            Prioridad = 4,
                            TiempoResolucion = 60,
                            TiempoRespuesta = 15,
                            Urgencia = 4
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 5, 2, 26, 28, 642, DateTimeKind.Utc).AddTicks(1876),
                            Descripcion = "SLA para incidentes de alta prioridad",
                            Impacto = 3,
                            IsActive = true,
                            IsDeleted = false,
                            Nombre = "Alto",
                            Prioridad = 3,
                            TiempoResolucion = 120,
                            TiempoRespuesta = 30,
                            Urgencia = 3
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 5, 2, 26, 28, 642, DateTimeKind.Utc).AddTicks(1878),
                            Descripcion = "SLA para incidentes de prioridad media",
                            Impacto = 2,
                            IsActive = true,
                            IsDeleted = false,
                            Nombre = "Medio",
                            Prioridad = 2,
                            TiempoResolucion = 480,
                            TiempoRespuesta = 60,
                            Urgencia = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 12, 5, 2, 26, 28, 642, DateTimeKind.Utc).AddTicks(1880),
                            Descripcion = "SLA para incidentes de baja prioridad",
                            Impacto = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Nombre = "Bajo",
                            Prioridad = 1,
                            TiempoResolucion = 2880,
                            TiempoRespuesta = 240,
                            Urgencia = 1
                        });
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ContactoTecnico")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .UseCollation("Modern_Spanish_CI_AS");

                    b.Property<string>("EscalacionProcedure")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .UseCollation("Modern_Spanish_CI_AS");

                    b.Property<string>("Instrucciones")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .UseCollation("Modern_Spanish_CI_AS");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .UseCollation("Modern_Spanish_CI_AS");

                    b.Property<bool>("RequiereAprobacion")
                        .HasColumnType("bit");

                    b.Property<string>("ResponsableArea")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .UseCollation("Modern_Spanish_CI_AS");

                    b.Property<int?>("TiempoResolucionMinutos")
                        .HasColumnType("int");

                    b.Property<int?>("TiempoRespuestaMinutos")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasFilter("[Codigo] IS NOT NULL");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AñosExperiencia")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Especialidad")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "FISEI",
                            Email = "admin@fisei.uta.edu.ec",
                            FirstName = "Administrador",
                            IsActive = true,
                            IsDeleted = false,
                            IsEmailConfirmed = true,
                            LastName = "Sistema",
                            PasswordHash = "$2a$11$KjLnhQkoD9HBy0sZQaxvKe5sBoELZbldjM1ywnR.wn9aAgOOXQr1K",
                            TipoUsuario = 4,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            AñosExperiencia = 8,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Soporte Técnico",
                            Email = "supervisor@fisei.uta.edu.ec",
                            Especialidad = "Redes y Sistemas",
                            FirstName = "Carlos",
                            IsActive = true,
                            IsDeleted = false,
                            IsEmailConfirmed = true,
                            LastName = "Mendoza",
                            PasswordHash = "$2a$11$r9PuDRz5A1J/7FHn3AXd5.Zg/AOUy0Ok/8sDSxJEKVGJYtFRlUdOK",
                            TipoUsuario = 3,
                            Username = "supervisor1"
                        },
                        new
                        {
                            Id = 3,
                            AñosExperiencia = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Soporte Técnico",
                            Email = "tecnico1@fisei.uta.edu.ec",
                            Especialidad = "Hardware y Software",
                            FirstName = "María",
                            IsActive = true,
                            IsDeleted = false,
                            IsEmailConfirmed = true,
                            LastName = "González",
                            PasswordHash = "$2a$11$wxqje4Ox3VO3RGljJA9Vp.9WByK3DpGbgDt2Bfde5awiLFBlY7.0e",
                            TipoUsuario = 2,
                            Username = "tecnico1"
                        },
                        new
                        {
                            Id = 4,
                            AñosExperiencia = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Soporte Técnico",
                            Email = "tecnico2@fisei.uta.edu.ec",
                            Especialidad = "Redes y Conectividad",
                            FirstName = "Luis",
                            IsActive = true,
                            IsDeleted = false,
                            IsEmailConfirmed = true,
                            LastName = "Ramírez",
                            PasswordHash = "$2a$11$9f5rP2P5qP5qP5qP5qP5qP5qP5qP5qP5qP5qP5qP5qP5qP5qP5qP5q",
                            TipoUsuario = 2,
                            Username = "tecnico2"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Ingeniería en Sistemas",
                            Email = "docente1@fisei.uta.edu.ec",
                            FirstName = "Ana",
                            IsActive = true,
                            IsDeleted = false,
                            IsEmailConfirmed = true,
                            LastName = "Pérez",
                            PasswordHash = "$2a$11$fS7059bDQD23mvMoKYCjoOvs7umhzDvu5tOW.lGwA7y6gzUWaNGo.",
                            Phone = "0998123456",
                            TipoUsuario = 1,
                            Username = "docente1"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Ingeniería en Sistemas",
                            Email = "estudiante1@fisei.uta.edu.ec",
                            FirstName = "José",
                            IsActive = false,
                            IsDeleted = false,
                            IsEmailConfirmed = false,
                            LastName = "Morales",
                            PasswordHash = "$2a$11$9f5rP2P5qP5qP5qP5qP5qP5qP5qP5qP5qP5qP5qP5qP5qP5qP5qP5q",
                            TipoUsuario = 1,
                            Username = "estudiante1"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Ingeniería Industrial",
                            Email = "estudiante2@fisei.uta.edu.ec",
                            FirstName = "Carmen",
                            IsActive = false,
                            IsDeleted = false,
                            IsEmailConfirmed = false,
                            LastName = "Torres",
                            PasswordHash = "$2a$11$9f5rP2P5qP5qP5qP5qP5qP5qP5qP5qP5qP5qP5qP5qP5qP5qP5qP5q",
                            TipoUsuario = 1,
                            Username = "estudiante2"
                        });
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.VotacionArticulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticuloId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EsPositivo")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ArticuloId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("VotacionesArticulo");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.ArchivoAdjunto", b =>
                {
                    b.HasOne("IncidentesFISEI.Domain.Entities.ArticuloConocimiento", "Articulo")
                        .WithMany("ArchivosAdjuntos")
                        .HasForeignKey("ArticuloId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IncidentesFISEI.Domain.Entities.Incidente", "Incidente")
                        .WithMany("ArchivosAdjuntos")
                        .HasForeignKey("IncidenteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IncidentesFISEI.Domain.Entities.Usuario", "SubidoPor")
                        .WithMany()
                        .HasForeignKey("SubidoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("Incidente");

                    b.Navigation("SubidoPor");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.ArticuloConocimiento", b =>
                {
                    b.HasOne("IncidentesFISEI.Domain.Entities.Usuario", "Autor")
                        .WithMany("ArticulosCreados")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IncidentesFISEI.Domain.Entities.CategoriaIncidente", "Categoria")
                        .WithMany("ArticulosConocimiento")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IncidentesFISEI.Domain.Entities.Usuario", "RevisadoPor")
                        .WithMany()
                        .HasForeignKey("RevisadoPorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Autor");

                    b.Navigation("Categoria");

                    b.Navigation("RevisadoPor");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.CategoriaIncidente", b =>
                {
                    b.HasOne("IncidentesFISEI.Domain.Entities.CategoriaIncidente", "ParentCategory")
                        .WithMany("SubCategorias")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.ComentarioArticulo", b =>
                {
                    b.HasOne("IncidentesFISEI.Domain.Entities.ArticuloConocimiento", "Articulo")
                        .WithMany("Comentarios")
                        .HasForeignKey("ArticuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IncidentesFISEI.Domain.Entities.Usuario", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.ComentarioIncidente", b =>
                {
                    b.HasOne("IncidentesFISEI.Domain.Entities.Usuario", "Autor")
                        .WithMany("Comentarios")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IncidentesFISEI.Domain.Entities.Incidente", "Incidente")
                        .WithMany("Comentarios")
                        .HasForeignKey("IncidenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Incidente");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.ConfiguracionNotificacion", b =>
                {
                    b.HasOne("IncidentesFISEI.Domain.Entities.Usuario", "Usuario")
                        .WithMany("ConfiguracionesNotificacion")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.EscalacionSLA", b =>
                {
                    b.HasOne("IncidentesFISEI.Domain.Entities.Incidente", "Incidente")
                        .WithMany()
                        .HasForeignKey("IncidenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IncidentesFISEI.Domain.Entities.SLA", "SLA")
                        .WithMany()
                        .HasForeignKey("SLAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Incidente");

                    b.Navigation("SLA");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.Incidente", b =>
                {
                    b.HasOne("IncidentesFISEI.Domain.Entities.ArticuloConocimiento", "ArticuloConocimiento")
                        .WithMany("IncidentesRelacionados")
                        .HasForeignKey("ArticuloConocimientoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IncidentesFISEI.Domain.Entities.Usuario", "AsignadoA")
                        .WithMany("IncidentesAsignados")
                        .HasForeignKey("AsignadoAId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IncidentesFISEI.Domain.Entities.CategoriaIncidente", "Categoria")
                        .WithMany("Incidentes")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IncidentesFISEI.Domain.Entities.Usuario", "CerradoPor")
                        .WithMany()
                        .HasForeignKey("CerradoPorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("IncidentesFISEI.Domain.Entities.Usuario", "ReabiertoPor")
                        .WithMany()
                        .HasForeignKey("ReabiertoPorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("IncidentesFISEI.Domain.Entities.Usuario", "ReportadoPor")
                        .WithMany("IncidentesReportados")
                        .HasForeignKey("ReportadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IncidentesFISEI.Domain.Entities.Servicio", "Servicio")
                        .WithMany("Incidentes")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ArticuloConocimiento");

                    b.Navigation("AsignadoA");

                    b.Navigation("Categoria");

                    b.Navigation("CerradoPor");

                    b.Navigation("ReabiertoPor");

                    b.Navigation("ReportadoPor");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.IncidenteRelacionado", b =>
                {
                    b.HasOne("IncidentesFISEI.Domain.Entities.Incidente", "IncidentePrincipal")
                        .WithMany("IncidentesRelacionados")
                        .HasForeignKey("IncidentePrincipalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IncidentesFISEI.Domain.Entities.Incidente", "IncidenteRef")
                        .WithMany()
                        .HasForeignKey("IncidenteRelacionadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IncidentePrincipal");

                    b.Navigation("IncidenteRef");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.LogNotificacion", b =>
                {
                    b.HasOne("IncidentesFISEI.Domain.Entities.Notificacion", "Notificacion")
                        .WithMany("LogsEnvio")
                        .HasForeignKey("NotificacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notificacion");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.Notificacion", b =>
                {
                    b.HasOne("IncidentesFISEI.Domain.Entities.Incidente", "Incidente")
                        .WithMany()
                        .HasForeignKey("IncidenteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IncidentesFISEI.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Notificaciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incidente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.RegistroTiempo", b =>
                {
                    b.HasOne("IncidentesFISEI.Domain.Entities.Incidente", "Incidente")
                        .WithMany("RegistrosTiempo")
                        .HasForeignKey("IncidenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IncidentesFISEI.Domain.Entities.Usuario", "Tecnico")
                        .WithMany()
                        .HasForeignKey("TecnicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Incidente");

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.Servicio", b =>
                {
                    b.HasOne("IncidentesFISEI.Domain.Entities.CategoriaIncidente", "Categoria")
                        .WithMany("Servicios")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.VotacionArticulo", b =>
                {
                    b.HasOne("IncidentesFISEI.Domain.Entities.ArticuloConocimiento", "Articulo")
                        .WithMany("Votaciones")
                        .HasForeignKey("ArticuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IncidentesFISEI.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.ArticuloConocimiento", b =>
                {
                    b.Navigation("ArchivosAdjuntos");

                    b.Navigation("Comentarios");

                    b.Navigation("IncidentesRelacionados");

                    b.Navigation("Votaciones");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.CategoriaIncidente", b =>
                {
                    b.Navigation("ArticulosConocimiento");

                    b.Navigation("Incidentes");

                    b.Navigation("Servicios");

                    b.Navigation("SubCategorias");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.Incidente", b =>
                {
                    b.Navigation("ArchivosAdjuntos");

                    b.Navigation("Comentarios");

                    b.Navigation("IncidentesRelacionados");

                    b.Navigation("RegistrosTiempo");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.Notificacion", b =>
                {
                    b.Navigation("LogsEnvio");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.Servicio", b =>
                {
                    b.Navigation("Incidentes");
                });

            modelBuilder.Entity("IncidentesFISEI.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("ArticulosCreados");

                    b.Navigation("Comentarios");

                    b.Navigation("ConfiguracionesNotificacion");

                    b.Navigation("IncidentesAsignados");

                    b.Navigation("IncidentesReportados");

                    b.Navigation("Notificaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
